Fixing issue "AttributeError: 'PosixPath' object has no attribute 'rfind'" Looks like when using Python 3.5 Path constructor cannot handle other Path objects. Sticking to strings instead resolved the issue. See https://docs.python.org/3.5/library/os.path.html#os.path.dirname and https://docs.python.org/3.6/library/os.path.html#os.path.dirname for reference. "Changed in version 3.6: Accepts a path-like object." closes #2